server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.145:1111
#暴露 actuator 监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
