server:
  port: 2002
spring:
  application:
    name: cloudalibaba-seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:3333
      sentinel:
        transport:
          port: 8719
          #sentinel 熔断限流监控服务（web平台）
          dashboard: 192.168.50.83:8080
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&character=UTF-8&serverTimezone=UTC
    username: root
    password: syq
    type: com.alibaba.druid.pool.DruidDataSource
#orm框架
#mybatis
mybatis:
  config-location: classpath:mybatis/mybatis.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  #sentinel 整合 openfeign
  sentinel:
    enabled: true