server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进eureka的服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guzy313/springcloud-config-2023-02-14.git #github仓库
          search-paths:
            - springcloud-config-2023-02-14
      #读取分支
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka