server:
  port: 7002
spring:
  application:
    #服务名称
    name: cloud-eureka-server7002
eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称 (在本地C:\Windows\System32\drivers\etc 路径下的host文件里面peizhi)
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #此处为集群配置，与其他的注册中心相互注册 (所以此处不能是自己)
      #多个写法 defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/