server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.83:3333
    # 熔断限流
    sentinel:
      transport:
        #配置sentinel的dashboard 【此处表示8080dashboard服务会监控当前服务】
        dashboard: localhost:8080
        #默认8719端口，如果占用会自动从8719 开始依次 +1 扫描,直到找到未被占用端口
        port: 8719
#暴露 actuator 监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
