server:
  port: 9527
spring:
  application:
    #服务名称
    name: cloud-gateway-gateway9527
  cloud:
    gateway:
      routes:
        - id: payment_route #路由的ID，没有固定的规则但要求唯一，建议配合服务名称
          uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/findAll/** #断言，路径相匹配的进行路由
        - id: payment_route2 #路由的ID，没有固定的规则但要求唯一，建议配合服务名称
          uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/findById/** #断言，路径相匹配的进行路由

eureka:
  client:
    #表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    #设置微服务 在注册中心的名称
    instance-id: gateway9527
    #展示微服务的ip地址
    prefer-ip-address: true