server:
  port: 7001
spring:
  application:
    #服务名称
    name: cloud-eureka-server7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称 (在本地C:\Windows\System32\drivers\etc 路径下的host文件里面peizhi)
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #此处为集群配置，与其他的注册中心相互注册 (所以此处不能是自己)
      #defaultZone: http://eureka7002.com:7002
  server:
    #设置为false则是关闭自我保护模式，无法检测到注册的微服务心跳则立刻注销该微服务(不设置默认为true)
    enable-self-preservation: true
    #检测心跳时间设置为60秒
    eviction-interval-timer-in-ms: 60000