server:
  port: 80
spring:
  application:
    #服务名称
    name: cloud-order-service-feign
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db01?useUnicode=true&character=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: syq
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.my.springcloud.entity

eureka:
  client:
    #表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #设置微服务 在注册中心的名称
    instance-id: order-feign80
    #展示微服务的ip地址
    prefer-ip-address: true