server:
  port: 8004
spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db01?useUnicode=true&character=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: syq
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.my.springcloud.entity
  cloud:
    zookeeper:
      connect-string: 192.168.50.145:2181
